### ISSUE TITLE
Find episodes

### ISSUE THREAD

**Issue by johnylab** [illuzor/Play-Button-For-Pocket-Casts#1]
I'm really sorry I don't know how to do this right.

I created a new repository that should be a branch of this one.

https://github.com/johnylab/Pocket-Casts-Remote-Control

Changes: It finds the episodes on a tab when the player is not open.

**Comment by illuzor** [comment]
Hello. Thank you. I see you are forked my repository. And now you can make pull request. Then i`ll review the changes.

**Comment by johnylab** [comment]
Hope it's working right now. Do you see the request?

**Comment by illuzor** [comment]
No. Something wrong

**Comment by johnylab** [comment]
I thing I was done a pull request to myself.

**Comment by illuzor** [comment]
Ok now. I will take a look. Thank you.

**Comment by illuzor** [comment]
I removed "play after tab open". It`s not working because contend loading is not instantaneous.
"Find episodes" works great.
Updated version soon will be in chrome webstore.
