### ISSUE TITLE
Port the extension on Microsoft Edge

### ISSUE THREAD

**Issue by ghost** [illuzor/Play-Button-For-Pocket-Casts#11]
I love your extension! I'd really like it if you would publish it for Microsoft Edge as well. 
Here's some instructions on how to do that: https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions
I followed the guide and managed to convert it on my machine - it works fine, except for the keyboard play/pause buttons.
Can you please have a look?

Thanks

**Comment by illuzor** [comment]
Hello. Can you share your code?

**Comment by illuzor** [comment]
No answer
