### ISSUE TITLE
Support for the 2.0 Beta Web Player

### ISSUE THREAD

**Issue by troyhayes** [illuzor/Play-Button-For-Pocket-Casts#12]
The beta for the new web player came out today, available at https://playbeta.pocketcasts.com/

Any chance we could get support for this or better to wait for the official release?

**Comment by illuzor** [comment]
Yes, of course. I will update it after 2.0 release.

**Comment by BenMusch** [comment]
FWIW, I will give this a shot over the weekend. Seems pretty straightforward

**Comment by illuzor** [comment]
**BenMusch**, I already did it. https://github.com/illuzor/Play-Button-For-Pocket-Casts/tree/version2
Just waiting for 2.0 release.

**Comment by BenMusch** [comment]
@illuzor oh, awesome! Thanks

**Comment by illuzor** [comment]
@MrTroot, @BenMusch if you want to test updated extension with Pocketcasts 2.0 beta:

1) Disable or remove current extension in chrome;
2) Download **source** folder from [version2 branch](https://github.com/illuzor/Play-Button-For-Pocket-Casts/tree/version2);
3) Open **Menu/More Tools/Extensions** in Chrome;
4) Enable **Developer mode**;
5) Click **Load Unpacked Extension** button and provide path to the **source** folder.

**Comment by illuzor** [comment]
http://s.illuzor.com/pc_chrome
http://s.illuzor.com/pc_firefox
