### ISSUE TITLE
Doesn't work after latest pocketcasts update.

### ISSUE THREAD

**Issue by WildGenius** [illuzor/Play-Button-For-Pocket-Casts#17]
Changelog from pocketcasts:

> Version 2.1 Build 59 20th February, 2019
🏳 Fixed a bug that prevented some non-English languages rendering correctly.
🔨 Fixed IE11. Not literally, but a usability issue specific to it.

**Comment by illuzor** [comment]
Thank you for report. Will be fixed soon.
