### ISSUE TITLE
Broken after last pocketcasts update.

### ISSUE THREAD

**Issue by WildGenius** [illuzor/Play-Button-For-Pocket-Casts#20]
Notes from pocketcasts:

>  Version 3.4
> 
> 14th October, 2020
> 
> Lots of small tweaks and performance enhancements. I know, that's not the low level of detail you expect from us but we really did work on a thousand little things instead of one giant thing for once 😉

**Comment by illuzor** [comment]
@WildGenius thank you for the report. Will be fixed soon.
