### ISSUE TITLE
Add media keys support

### ISSUE THREAD

**Issue by kudos** [illuzor/Play-Button-For-Pocket-Casts#3]
https://developer.chrome.com/extensions/commands

> Supported keys: [...] and the Media Keys (MediaNextTrack, MediaPlayPause, MediaPrevTrack, MediaStop).

**Comment by illuzor** [comment]
Hello. I thought about it, but i think it will be conflict with other media extensions, will it?

**Comment by kudos** [comment]
I think if you already have an extension that shortcuts to the media keys, additional extensions don't get to register themselves on them. This is evidenced by the use of `suggested_key` for setting it.

**Comment by gausie** [comment]
:+1:

**Comment by kudos** [comment]
[Streamkeys](https://chrome.google.com/webstore/detail/streamkeys/ekpipjofdicppbepocohdlgenahaneen/reviews?hl=en-US) added Pocketcasts support a while back  and it works pretty well. I'm sure this extension is still useful to people, but it might be worth just pointing users there for this functionality. Feel free to close.

**Comment by illuzor** [comment]
Done.
